name: EGS FEED

on:
  schedule:
    - cron: '* * * * *' # Jalankan setiap jam
  workflow_dispatch: # Memungkinkan pemicu manual

jobs:
  generate-rss:
    runs-on: ubuntu-latest

    steps:
      # Checkout kode dari repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Setup Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pymongo beautifulsoup4 lxml
          
      # Install Rclone
      - name: Install Rclone
        run: |
         sudo -v ; curl https://rclone.org/install.sh | sudo bash -s beta 

      # Generate RSS Feed
      - name: Generate RSS Feed
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }} # MongoDB URI dari Secrets
        run: |
          python EGS-E.py # Pastikan `script.py` adalah nama file Python Anda

      # Configure Rclone
      - name: Configure Rclone
        run: |
          echo '${{ secrets.RCLONE_CONFIG }}' > rclone.conf

      # Unggah file XML ke remote menggunakan rclone
      - name: Upload to Remote
        env:
          RCLONE_CONFIG: ${{ secrets.RCLONE_CONFIG }} > rclone.conf # Rclone Config dari Secrets
        run: |
          rclone copy EGS-E.xml ab:Arc.BiHU.0x/0x/0x/XML --quiet --config rclone.conf
